### ISSUE TITLE
Can't load script, "ImportError: No module named 'PySide2'

### ISSUE THREAD

**Issue by ahalota** [agisoft-llc/metashape-scripts#16]
I can't load split_in_chunks_dialog.py on one of my installs of Metashape.

```
2020-01-28 11:22:09     from PySide2 import QtGui, QtCore, QtWidgets
2020-01-28 11:22:09 ImportError: No module named 'PySide2'
2020-01-28 11:22:09 Error: No module named 'PySide2'
```

It seems the python install doesn't have PySide2 library available, but where should it be installed?

This is if I load the script in via the Console in Metashape 1.5.1

**Comment by PolarNick239** [comment]
Hi,

PySide2 package bundled with Metashape installation, but it seems that something gone wrong and this package was broken.

1) Have you installed any additional packages in bundled Python?
2) Please execute ```pip freeze``` from bundled python and provide me output (to run bundled pip do like described [here](https://agisoft.freshdesk.com/support/solutions/articles/31000136860-how-to-install-external-python-module-to-metashape-professional-package), but instead of ```pip install python_module_name``` use ```pip freeze```).
3) Make clean install: uninstall Metashape, manually delete whole Metashape folder - Program Files/Agisoft/Metashape Pro, install Metashape again (if you need 1.5.1 version - just change number in [URL](http://download.agisoft.com/metashape-pro_1_6_1_x64.msi)).
4) Try again. If it still doesn't work - please do step 2 again and provide me both ```pip freeze``` outputs.

**Comment by PolarNick239** [comment]
Please feel free to reopen issue if you still have the problem.

**Comment by ahalota** [comment]
Oh! I did make some additions to the install of python, I'd forgotten that I did that. I switched to a clean install of 1.6.1. and it worked

**Comment by PolarNick239** [comment]
Nice! :)
