### ISSUE TITLE
save estimated reference error

### ISSUE THREAD

**Issue by Pap1956** [agisoft-llc/metashape-scripts#43]
with latest version 1.8.3, script https://github.com/agisoft-llc/metashape-scripts/blob/master/src/save_estimated_reference.py  returns an error when calling the getAntennaTransform() function.

The problem seems to be that sensor.antenna.location_ref and sensor.antenna.rotation_ref return None in latest version while it was returning a Vector in previous versions, see attachment comparing 1.7.3 and 1.8.3 behavior...
Modify message
![Captura](https://user-images.githubusercontent.com/74811441/164883575-987c7cb2-03f2-4bd0-9bdf-a9d9ed422c05.JPG)

**Comment by PolarNick239** [comment]
Thanks for reporing this!

Scripts save_estimated_reference.py and quick_layout.py were broken in 1.8.3, because Python API was changed in release 1.8.3 - since then if there are no reference location/rotation - they will be None (instead of zero vector like before).

Scripts were fixed to handle this change properly.
