### ISSUE TITLE
Get Footprint from DEM or OrthoMOsaic in Ortho Tab

### ISSUE THREAD

**Issue by kaichand9** [agisoft-llc/metashape-scripts#48]
Hi, here  is a script named as "[footprints_to_shapes.py](https://github.com/agisoft-llc/metashape-scripts/blob/master/src/footprints_to_shapes.py)". It given footprint of camera opened in chunk.
Is there a way that this script, can provides the precise footprint boundary of the raster in Ortho tab using DEM or OrthoMosaic generated i.e. See below image as example _Footprint to Raster
![Capture11111Metashape](https://user-images.githubusercontent.com/39769675/180734774-3c18bfe6-e520-421d-858b-789c8c384aab.JPG)

**Comment by PolarNick239** [comment]
Hi,

sadly, no, footprints_to_shapes.py can't provide the precise footprint boundary of the raster, because it just project 4 corners of each photo on the surface.

**Comment by PeterBetlem** [comment]
Would this be in the pipeline? A similar function must already be available through the Area() functions. It would be great if it were accessible as an API call, e.g. resulting in a multipolygon shape.

**Comment by PolarNick239** [comment]
Hi, Peter.

Currently this feature is not in the development. You can post this feature-request on forum - https://www.agisoft.com/forum/index.php?board=11.0 - in such way it will be possible to discuss it with other users and it will be simpler for us to track feature ideas.

**Comment by PolarNick239** [comment]
This feature is not available. It is not under development at the moment, as other features have higher priority and provide greater benefit to a larger number of users.

If you can describe why you need generating a vector shape (e.g., a polygon/shapefile) that outlines the DEM/orthomosaic boundary, it will help us better assess the value of this feature. In other words, how do you plan to use this boundary?

Please also specify the boundary accuracy you would expect. (If you require absolute accuracy, the geometry would become extremely detailed and large, since it would need to trace every edge of each boundary pixel with individual line segments.)
