### ISSUE TITLE
Support question to "Style Transfer Script"

### ISSUE THREAD

**Issue by MarcusMorba** [agisoft-llc/metashape-scripts#54]
I found this support article: https://agisoft.freshdesk.com/support/solutions/articles/31000158881-style-transfer-for-3d-model

But the Script is not longer available for download > https://github.com/agisoft-llc/photoscan-scripts/blob/master/src/model_style_transfer.py

Please update the support article. Is style transfer still possible?

**Comment by PolarNick239** [comment]
Hi, it is still available and should work in Metashape 1.6 version - https://github.com/agisoft-llc/metashape-scripts/blob/1.6/src/model_style_transfer.py It was the last release where this script was working.

Metashape 1.7 and 1.8 bundles Python 3.8 (instead of Python 3.5 for Metashape 1.6), but there are no **Tensorflow 1.x** for Python 3.8. And while **Tensorflow 2.x** is available - it is incompatible with [**Lucid**](https://github.com/tensorflow/lucid#lucid) library which is used a lot in this script.

So, sadly, we don't have plans to update this script for Metashape releases 1.7+.

Thanks for reporting about this, we will update freshdesk article to make clear that it works only on Metashape 1.6.

**Comment by PolarNick239** [comment]
Support article updated with note about Metashape 1.6 - https://agisoft.freshdesk.com/support/solutions/articles/31000158881-style-transfer-for-3d-model

**Comment by MarcusMorba** [comment]
Thanks.
