### ISSUE TITLE
change automatic_masking script rembg model

### ISSUE THREAD

**Issue by henrypearce4D** [agisoft-llc/metashape-scripts#65]
I'm testing the automatic_masking script and rembg with different models

https://github.com/agisoft-llc/metashape-scripts/blob/master/src/automatic_masking.py

In the rembg code this command changes the model
`rembg i -m isnet-general-use path/to/input.png path/to/output.png`

Is it possible to change the model used the `isnet-general-use` ?

**Comment by PolarNick239** [comment]
Hi, Henry.

Now, you can change name of used AI-model in this line: https://github.com/agisoft-llc/metashape-scripts/blob/50f0fbcc131154ace48b97bc33638851990c90a7/src/automatic_masking.py#L35

Why are you interested in ```isnet-general-use``` model? Is it better then ```unet``` in your case?

**Comment by henrypearce4D** [comment]
Hi, yes from testing the models, isnet-general-use produced better results for our data.

Thankyou for making that addition to the script to choose the model.

I have a question, the masks created with rembg have a gradient of black and white, does metashape not support masks like this, does it only support pure white (1) and pure black (0) masks?

**Comment by PolarNick239** [comment]
> does metashape not support masks like this, does it only support pure white (1) and pure black (0) masks

In Metashape masks used as a guiadance "what pixels should be ignored?". So mask interpretation is binary. In case of cameras alignment we just want to mask out background pixels - to get rid of keypoints on background. 

Also, this script generates masks without alpha-matting because in such way rembg works much faster.

Feel free to re-open this issue if needed.
