### ISSUE TITLE
export_for_gaussian_splatting.py possible to export a dense point cloud also?

### ISSUE THREAD

**Issue by luuude** [agisoft-llc/metashape-scripts#67]
Is it possible to add some code to be able to export a dense cloud instead? It should be more correct for where to calculate splats?

**Comment by PolarNick239** [comment]
Currently Gaussian Splatting requires SfM points as input. They differ from generic dense cloud - SfM points (tie points) have information about "what cameras can see each point for sure".

If Gussian Splatting uses only their coordinates from SfM points - it will be pretty straight forward to update export_for_gaussian_splatting.py. It should be enough to update code with exporting point cloud - f.e. [here](https://github.com/agisoft-llc/metashape-scripts/blob/d96165978748c93de78f8ea1dc9bca7886b91b26/src/export_for_gaussian_splatting.py#L407-L416) you should export ```num=0```, i.e. "each point doesn't have projections". And in [lines above](https://github.com/agisoft-llc/metashape-scripts/blob/d96165978748c93de78f8ea1dc9bca7886b91b26/src/export_for_gaussian_splatting.py#L388C5-L405) - you need to export all points from dense cloud (warning - it can be slow because it is slow to iterate over hundred millions of elements).

Currently we don't have such plans. If somebody will be interested and after such experiment it becomes clear that such point cloud is supported in Gaussian Splatting and results are improved a lot - we are open for Pull Requests.

**Comment by luuude** [comment]
Ok then I understand. So a follow up question then. Would it be possible to create more tiepoints based on the depth maps? What I am looking for is a more precise description of the real scene to get less "floaters" in gaussian splatting.

**Comment by PolarNick239** [comment]
> Would it be possible to create more tiepoints based on the depth maps?

Yes, it should work. Possible problems:

- I don't know what maximum size of input point cloud can be processed with Gaussian Splatting, so it can fail due to large size of input point cloud
- It is easy to get single camera projection for each point generated with depth map, but may be Gaussian Splatting relies on fact that each input point has many camera projections (this is always true in case of SfM point cloud)
