### ISSUE TITLE
Merge camera calibration groups by lens type

### ISSUE THREAD

**Issue by henrypearce4D** [agisoft-llc/metashape-scripts#74]
Is there a script to merge camera calibration groups by lens type?

I understand that the camera calibration groups cameras by camera serial name. 
To merge by lens it is a very slow and manual process to select all cameras with the same lens and merge groups. 

Does a script exist to do this?

**Comment by PolarNick239** [comment]
No, there is no such script. Because it is done automatically in Metashape itself at stage of adding images.

So the question is why your images were splitted into different calibration groups? For example, such splitting is done if images have different focal length information in EXIF tags, camera model name or image resolution.

If you can provide reproducer - please send it to us at support@agisoft.com with link to this issue. So we will be able to reproduce and analyze why images were splitted into different calibration groups.

**Comment by henrypearce4D** [comment]
Ok I will send a link of an image set to the support email now.

Perhaps it is because our images are from machine vision cameras and there is extra exif tags in the files that metashape is picking up?

**Comment by PolarNick239** [comment]
Thank you, in a few days we will analyze why cameras were not grouped together, and if this is unexpected behaviour - we will fix this.

About your use-case:
1) It seems that these cameras are really different and takes photos simultaneously, in such case they should be splitted into separate camera groups for better alignment results.
2) Or even better - they should be splitted into different pre-calibrated camera groups.

**Comment by henrypearce4D** [comment]
Could you explain;

  "2. Or even better - they should be splitted into different pre-calibrated camera groups."
  
Do you mean save and re-use camera calibration per camera using the .xml method?  
  
We understand that we should get better results from using unique calibrations, but this results in the undistorted images w x h size also being unique everytime. By merging groups with the same type lens the images sets are easier to work with.

**Comment by PolarNick239** [comment]
Yes, I mean unique calibrations. Because for different sensors this is important to get good alignment (and thus - surface reconstruction/texture).

> By merging groups with the same type lens the images sets are easier to work with.

Can you please elaborate what kind of problems do you have when project has multiple camera groups (one per image)? I ask because we try to provide good results with easy processing. And in such project per-image camera group is a best way to have good results - so may be we need to improve something in UI so that it will be easier to work with such project?

**Comment by PolarNick239** [comment]
> Thank you, in a few days we will analyze why cameras were not grouped together, and if this is unexpected behaviour - we will fix this.

Your images have EXIF tag "Serial Number" (exiftool is very handful to check EXIF tags), so Metashape splits their calibration groups on per-image basis, because different camera sensors should be optimized in Align Photos with personal parameters (per-image focal length and other calibration parameters). Because each sensor is a bit different - because of imperfection of camera sensors production.

**Comment by henrypearce4D** [comment]
Thanks for checking the images, so it was as I expected - because of the serial number tag.

The reason for wanting to group the camera calibration is because sometimes the subject does not fill the frame, meaning the calibration is bad and export for gaussian splatting crops the images massively to the part of the image of where the subject is in frame, and using another calibration of the same type corrects this.

Also it makes the images easier to work with outside of metashape having the w x h match, as some further processing can require this be consistent.

**Comment by PolarNick239** [comment]
Got it, thanks for details about your use-case.

I think the easiest workaround is to use exiftool (or another tool) to remove Serial Number tag from all images before processing them in Metashape.

**Comment by henrypearce4D** [comment]
Thankyou for the suggestion.

Just so I know, should it be possible to create a script that I described to group the camera lenses into groups automatically? 
I attempted it with the python API but could not get something working.

Can the API work with the Camera Calibration in this way?

**Comment by PolarNick239** [comment]
Yes, it should work. You can look at similar script [here](https://www.agisoft.com/forum/index.php?topic=6383.msg30864#msg30864).
