### ISSUE TITLE
Why does using scripts 'src/export_for_gaussian_splatting.py' cause image resolution to decrease?

### ISSUE THREAD

**Issue by jiangxb98** [agisoft-llc/metashape-scripts#87]
When I used thie [script](https://github.com/agisoft-llc/metashape-scripts/blob/master/src/export_for_gaussian_splatting.py) to generate colmap data, I found that the output image resolution was reduced

**Comment by PolarNick239** [comment]
Hi!

Script generates undistorted images, because of this - lots of black pixels can appear near edges similar to this example:

![image](https://github.com/agisoft-llc/metashape-scripts/assets/1218605/56b5535f-52cf-40f0-9693-97a324f06169)

And black zones lead to bad gaussian splatting results. So script crops the output undistorted image to its inner part like this:

![image](https://github.com/agisoft-llc/metashape-scripts/assets/1218605/0cea4555-bb12-40e6-a547-1ec0477ef7c5)
